import type { Candidate } from "./types";

// Mocked candidate pool — wire to the Workable API server-side later.
// Pull resume, cover letter, application answers, salary, and logistics from
// Workable; Fireflies recordings/transcripts list per candidate.
export const CANDIDATES: Candidate[] = [
  // =================== PRASHANTHI — survivor ===================
  {
    id: "prashanthi",
    rank: 1,
    name: "Prashanthi P.",
    role: "Senior Clinical Data Manager",
    company: "Quartz Dx",
    salary: "$100k",
    salaryNum: 100,
    decision: "interview",
    rev: "conallPos",
    revNote: "Best data-integrity evidence in the pool; wants the first slot.",
    why: "Best data-integrity evidence in the pool — query-resolution and lock cycles with real mechanics.",
    flag: "No IVD / diagnostics domain — all experience is pharma EDC.",
    next: "Screen",
    survivor: true,
    askTier: "below",
    askNote: "$8k under pool median",
    roLevel: "RO-4",
    roVsPool: "Mid-senior IC — in line with the role",
    mismatch: false,
    mismatchRead:
      "Below-median ask for the strongest file. Ask sits under her demonstrated level — value, not risk.",
    timeline: [
      { type: "edu", period: "2011–2015", org: "UC Davis", role: "BS, Molecular Biology", tenure: "4.0 yrs", scope: "Science degree — connects directly to clinical data", lang: "—", signal: "Connected" },
      { type: "role", period: "2015–2017", org: "Cerulean CRO", role: "Clinical Data Associate", tenure: "2.0 yrs", scope: "Entry execution — query handling, CRF tracking", lang: "Reads RO-1, scope RO-1 — matched", signal: "Learning" },
      { type: "role", period: "2017–2019", org: "Cerulean CRO", role: "Clinical Data Coordinator", tenure: "2.0 yrs", scope: "Owns a study’s query lifecycle", lang: "Reads RO-2, scope RO-2 — matched", signal: "Positive" },
      { type: "role", period: "2019–2022", org: "Helix Therapeutics", role: "Clinical Data Manager", tenure: "3.0 yrs", scope: "Owns eCRF build + lock for oncology", lang: "Reads RO-3, scope RO-3 — matched", signal: "Promotion" },
      { type: "cert", period: "2021", org: "SCDM", role: "Certified Clinical Data Manager (CCDM)", tenure: "—", scope: "Domain certification, mid-career", lang: "—", signal: "Cert" },
      { type: "role", period: "2022–now", org: "Quartz Dx", role: "Senior Clinical Data Manager", tenure: "3.2 yrs", scope: "4 concurrent studies; portfolio edit-check standards", lang: "Reads RO-4, scope RO-4 — matched", signal: "Positive" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I am applying because I want to own data quality in a setting where the assay result is the endpoint, not a secondary measure.", comment: "Correct IVD framing — she understands what makes RDI different. Specific, not boilerplate.", kind: "good" },
        { t: "My background is pharmaceutical EDC, but the discipline — clean lock, defensible queries, audit-ready trails — is the same discipline RDI needs.", comment: "Names her own domain gap honestly and argues the transfer. Worth testing live, but this is candor, not spin.", kind: "good" },
        { t: "I have followed RDI’s Lumos program and the FebriDx clearance, and that is the kind of outcome I want my data work to stand behind.", comment: "Specific, real reference to RDI’s actual work. She did her homework.", kind: "good" },
      ],
    },
    answers: [
      { q: "Q2 — Walk us through your hardest database lock.", a: "A late protocol amendment changed two derived endpoints after 60% enrolment. I re-specified edit checks, re-queried 400+ affected records, and held the lock 9 days rather than lock dirty.", comment: "Held the line on a dirty lock under timeline pressure — names the endpoints, the records, the tradeoff. Exactly the instinct RDI wants.", kind: "good" },
      { q: "Q3 — How do you keep a study audit-ready?", a: "Every query has an owner, a reason code, and a resolution trail; I reconcile against central lab weekly so nothing piles up before lock.", comment: "Concrete mechanics, not adjectives.", kind: "good" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Pasadena, CA",
      distance: "~28 mi / 35–50 min",
      likelihood: "High",
      read: "Already in LA County and commuting distance to Van Nuys. No relocation needed; the 5-day on-site ask is realistic for her.",
      signals: [
        { mark: "+", t: "Pasadena address on file — established in the LA basin, not relocating." },
        { mark: "+", t: "Current role at Quartz Dx is on-site in Glendale; she already commutes a similar corridor." },
      ],
    },
    fireflies: [
      { title: "Screening call — Prashanthi P. / Rob", date: "Mar 24, 2026", dur: "32 min", transcript: "Rob: Thanks for making time. Start with the hardest database lock you have run.\nPrashanthi: A Phase III where a late amendment changed two derived endpoints after 60% enrolment. I re-specified the edit checks, re-queried about 400 records, and held the lock nine days rather than lock dirty.\nRob: What would have shipped if you had locked on time?\nPrashanthi: Two endpoints derived on the old logic — it would have been an audit finding.\nRob: We are IVD here. The assay result is the endpoint, samples are keyed to timepoints. Where would a mislabeled aliquot surface in your process?\nPrashanthi: Honestly, not somewhere I have owned directly. I would reconcile on the sample and timepoint key, but I have not run assay-driven data before.\nRob: That is the gap. Otherwise the instincts are exactly right." },
    ],
    interview: {
      title: "Summary of interview with Rob — March 24, 2026",
      fit: "Strong fit on data-integrity instincts; the IVD-transfer concern narrowed but did not fully close. Rob recommends a short second conversation with the lab before an offer.",
      points: [
        { mark: "+", t: "Walked through the 9-day held lock unprompted, with exact edit-check detail — the ownership is real, not a résumé line." },
        { mark: "+", t: "Asked sharp questions about RDI sample/timepoint keys; engaged with the IVD model rather than treating it as a generic therapeutic area." },
        { mark: "–", t: "Still no hands-on IVD reps; would need a ramp on assay-driven endpoints. Trainable, not yet proven." },
      ],
    },
    redFlags: [],
  },

  // =================== MOHAMMED — survivor / career switcher ===================
  {
    id: "mohammed",
    rank: 2,
    name: "Mohammed A.",
    role: "Hybrid Lab / Data / AI Operations",
    company: "Benchmark Bio",
    salary: "$95k",
    salaryNum: 95,
    decision: "interview",
    rev: "none",
    revNote: "No human review yet — Conall should take the first screen before Lara invests time.",
    why: "Rare hybrid signal: lab work, data review, AI agent-building, instrument troubleshooting.",
    flag: "No clinical-trial or FDA-documentation experience.",
    next: "Screen",
    survivor: true,
    askTier: "below",
    askNote: "under pool median",
    roLevel: "RO-3",
    roVsPool: "Mid IC — below the title bar, fair for a switcher",
    mismatch: false,
    mismatchRead:
      "Below-median ask for a rare hybrid skill set. If the clinical-trial gap is trainable, the ask is upside, not risk.",
    timeline: [
      { type: "edu", period: "2013–2017", org: "Cal State Northridge", role: "BS, Biochemistry", tenure: "4.0 yrs", scope: "Bench science degree — connects to lab, not to trials", lang: "—", signal: "Connected" },
      { type: "role", period: "2017–2019", org: "Aster Genomics", role: "Research Associate", tenure: "2.0 yrs", scope: "Wet-lab assay execution + QC", lang: "Reads RO-2, scope RO-2 — matched", signal: "Positive" },
      { type: "role", period: "2019–2021", org: "Aster Genomics", role: "Lab + Data Associate", tenure: "2.0 yrs", scope: "Added data review to bench work — the switch begins", lang: "Reads RO-2, scope RO-2 — matched", signal: "Switched" },
      { type: "cert", period: "2022", org: "DeepLearning.AI", role: "AI / prompt-engineering certificate", tenure: "—", scope: "Self-directed; the AI tooling is self-taught", lang: "—", signal: "Cert" },
      { type: "role", period: "2021–now", org: "Benchmark Bio", role: "Lab Ops & Data Analyst", tenure: "3.5 yrs", scope: "Lab ops + data review + AI tooling + instrument QC", lang: "Reads RO-3, scope RO-3 — matched, no inflation", signal: "Positive" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I build tools around the parts of lab work that waste people’s time, instead of treating AI as a buzzword.", comment: 'Builder framing tied to real workflow pain — not "AI-powered synergy" filler. Reads human.', kind: "good" },
        { t: "I have not run a clinical trial, but I have spent four years where the data and the instrument are the same problem, and I want to bring that to a regulated setting.", comment: "Names the gap up front and frames the switch honestly. The exact thing to pressure-test live.", kind: "ask" },
      ],
    },
    answers: [
      { q: "Q3 — Describe a workflow bottleneck you removed.", a: "Kit-cost allocation took a full day each week. I structured the inputs, wrote the agent’s instructions, caught two hallucinated allocations in testing, and added a human check before anything posts.", comment: "Names the failure modes and a human-in-the-loop check — sounds like real ownership, not ChatGPT gloss. Verify the file structure on the call.", kind: "good" },
      { q: "Q1 — Why this role?", a: "I have not worked on a clinical trial or an FDA submission, but I want to.", comment: "Self-disclosed gap. Honest — but this is the whole risk. Test whether he respects protocol he has never lived under.", kind: "ask" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Van Nuys, CA",
      distance: "~3 mi / 10 min",
      likelihood: "High",
      read: "Lives in Van Nuys; current Benchmark Bio role is on-site locally. The 5-day ask is a non-issue for him.",
      signals: [
        { mark: "+", t: "Local Van Nuys address — no relocation, minimal commute." },
        { mark: "+", t: "Current and prior roles were both on-site lab positions — used to in-person, hands-on work." },
      ],
    },
    redFlags: [],
  },

  // =================== JOHN — short screen / comp ===================
  {
    id: "john",
    rank: 3,
    name: "John D.",
    role: "Clinical Data Lead",
    company: "Meridian CRO",
    salary: "$140k",
    salaryNum: 140,
    decision: "short",
    rev: "conallConcern",
    revNote: "Strong operator on paper but salary and motivation read like a flight risk; short screen only.",
    why: "Strong operator profile, but $140k ask tops the pool and motivation for a smaller shop is unclear.",
    flag: "Possible comp flight risk; why leave a larger CRO for RDI is unanswered.",
    next: "Short screen",
    survivor: true,
    askTier: "top",
    askNote: "tops the pool by $25k+",
    roLevel: "RO-5",
    roVsPool: "Manager level — highest in the pool",
    mismatch: false,
    mismatchRead:
      "Top ask matched by a genuine manager-level RO. The question is fit and motivation for a smaller, hands-on role — not whether the level justifies the number.",
    timeline: [
      { type: "edu", period: "2006–2010", org: "Rutgers", role: "BS, Biology", tenure: "4.0 yrs", scope: "Science degree — connects to path", lang: "—", signal: "Connected" },
      { type: "role", period: "2012–2015", org: "Apex Pharma", role: "Clinical Data Coordinator", tenure: "3.0 yrs", scope: "Study-level query ownership", lang: "Reads RO-2, scope RO-2 — matched", signal: "Positive" },
      { type: "role", period: "2015–2018", org: "Meridian CRO", role: "Clinical Data Manager", tenure: "3.0 yrs", scope: "Owns study DM", lang: "Reads RO-3, scope RO-3 — matched", signal: "Promotion" },
      { type: "role", period: "2018–now", org: "Meridian CRO", role: "Clinical Data Lead", tenure: "7.0 yrs", scope: "Leads 6 DMs across a 20-study portfolio", lang: "Reads RO-5, scope RO-5 — matched", signal: "Positive" },
    ],
    cover: { hasLetter: false, lines: [] },
    answers: [
      { q: "Q1 — Why this role?", a: "Looking for a new challenge and growth.", comment: "Generic. Does not explain leaving a larger CRO for a smaller, more hands-on shop — and there’s no cover letter to fill the gap. This is the whole question.", kind: "thin" },
    ],
    logistics: {
      mode: "Remote / relocation unclear",
      location: "Princeton, NJ",
      distance: "~2,800 mi — would relocate",
      likelihood: "Low",
      read: "East-coast based with no LA history on file and no stated relocation plan. A 5-day Van Nuys role is a hard ask; confirm relocation intent before any full interview.",
      signals: [
        { mark: "–", t: "No prior LA-area roles or addresses — relocation would be a cold move." },
        { mark: "–", t: "No relocation statement in the application; combined with the top-of-pool ask, raises the flight-risk read." },
      ],
    },
    redFlags: [],
  },

  // =================== WEI — verify ===================
  {
    id: "wei",
    rank: 4,
    name: "Wei C.",
    role: "Clinical Data Manager",
    company: "Northstar Labs",
    salary: "$108k",
    salaryNum: 108,
    decision: "verify",
    rev: "second",
    revNote: "Promising file, but salary field is blank and one claim has no résumé support.",
    why: "Promising EDC file, but salary field is blank and a key ownership claim has no résumé support.",
    flag: "Missing salary + one unsupported claim. One follow-up before any interview slot.",
    next: "Verify",
    survivor: false,
    askTier: "mid",
    askNote: "salary field left blank",
    roLevel: "RO-3",
    roVsPool: "Mid IC — in range for the role",
    mismatch: true,
    mismatchRead:
      "Cannot place value: the salary field is blank. Resolve comp before ranking — a promising file with an unknown price.",
    timeline: [
      { type: "edu", period: "2012–2016", org: "University of Washington", role: "BS, Bioengineering", tenure: "4.0 yrs", scope: "Technical degree — connects to EDC", lang: "—", signal: "Connected" },
      { type: "role", period: "2016–2020", org: "Cardia Trials", role: "Data Coordinator", tenure: "4.0 yrs", scope: "Query handling, CRF tracking", lang: "Reads RO-2, scope RO-2 — matched", signal: "Positive" },
      { type: "role", period: "2020–now", org: "Northstar Labs", role: "Clinical Data Manager", tenure: "5.0 yrs", scope: "eCRF build + query mgmt, cardiology studies", lang: "Reads RO-3, scope RO-3 — matched", signal: "Positive" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I have spent five years making cardiology study data clean and lockable, and I want to do the same where the diagnostic itself is the question.", comment: "Solid, specific framing. No red flags in the letter.", kind: "good" },
      ],
    },
    answers: [
      { q: "Q2 — Biggest data-quality win.", a: "Rebuilt lab reconciliation that caught a systematic unit-conversion error across a study.", comment: "Strong if true — but nothing in the résumé mentions reconciliation ownership. Get the specifics in a written follow-up before a slot.", kind: "ask" },
    ],
    logistics: {
      mode: "Hybrid / relocation likely",
      location: "Seattle, WA",
      distance: "~1,100 mi — would relocate",
      likelihood: "Medium",
      read: "Seattle-based with no LA history. Says open to relocation in the logistics field, but no prior LA ties to confirm it would stick. Verify alongside the salary follow-up.",
      signals: [
        { mark: "+", t: "Stated open to relocation for the right role." },
        { mark: "–", t: "No prior LA-area address or employer to anchor the relocation claim." },
      ],
    },
    redFlags: [],
  },

  // =================== SOFIA — short ===================
  {
    id: "sofia",
    rank: 5,
    name: "Sofia M.",
    role: "Data Manager II",
    company: "Veris Health",
    salary: "$92k",
    salaryNum: 92,
    decision: "short",
    rev: "none",
    revNote: "No human review yet.",
    why: "Adjacent pharmacovigilance + EDC depth; could grow into the role but not a direct CDM match yet.",
    flag: "Breadth over depth — has not owned a full lock cycle solo.",
    next: "Short screen",
    survivor: false,
    askTier: "below",
    askNote: "lowest ask in the screen group",
    roLevel: "RO-3",
    roVsPool: "Mid IC — slightly under the role bar",
    mismatch: false,
    mismatchRead:
      "Below-median ask for a develop-hire. Fair if RDI wants to grow someone into the lock role.",
    timeline: [
      { type: "edu", period: "2014–2018", org: "Boston University", role: "BS, Public Health", tenure: "4.0 yrs", scope: "Adjacent degree — pharmacovigilance, not data", lang: "—", signal: "Connected" },
      { type: "role", period: "2018–2021", org: "SafetyFirst PV", role: "Pharmacovigilance Associate", tenure: "3.0 yrs", scope: "Safety reconciliation, case intake", lang: "Reads RO-2, scope RO-2 — matched", signal: "Positive" },
      { type: "role", period: "2021–now", org: "Veris Health", role: "Data Manager II", tenure: "4.0 yrs", scope: "Supported eCRF build + safety reconciliation (vaccine)", lang: "Reads RO-3, supported not owned", signal: "Ask" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "My strength is the seam between safety data and clinical data, and I want to own more of the clinical side.", comment: "Honest about wanting to grow into the role. Reasonable.", kind: "neutral" },
      ],
    },
    answers: [
      { q: "Q2 — Have you owned a database lock end to end?", a: "I have supported several locks and led reconciliation, and I am ready to own one fully.", comment: '"Supported", not "owned" — the exact distinction to test. Honest framing, but she’d be a develop-hire.', kind: "ask" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Long Beach, CA",
      distance: "~35 mi / 45–70 min",
      likelihood: "Medium",
      read: "In LA County but a long Van Nuys commute from Long Beach. Feasible but ask whether the 5-day drive is sustainable for her.",
      signals: [
        { mark: "+", t: "Already LA-based — no relocation." },
        { mark: "–", t: "Long Beach → Van Nuys is a heavy daily commute; confirm willingness." },
      ],
    },
    redFlags: [],
  },

  // =================== DANIEL — hold / mismatch ===================
  {
    id: "daniel",
    rank: 14,
    name: "Daniel O.",
    role: "Clinical Data Manager",
    company: "Atlas Trials",
    salary: "$120k",
    salaryNum: 120,
    decision: "hold",
    rev: "none",
    revNote: "No human review yet.",
    why: "Clean, professional file but weak relevance — does not beat the current top of the pool.",
    flag: "Removes little of the burden the role exists to remove.",
    next: "Hold",
    survivor: false,
    askTier: "high",
    askNote: "$12k over median",
    roLevel: "RO-3",
    roVsPool: "Mid IC — below his ask",
    mismatch: true,
    mismatchRead:
      "High-tier ask, mid-tier RO level. Competent but not differentiating — paying near top-of-pool comp for RO-3 scope.",
    timeline: [
      { type: "edu", period: "2010–2014", org: "Ohio State", role: "BS, Biology", tenure: "4.0 yrs", scope: "Science degree — connects", lang: "—", signal: "Connected" },
      { type: "role", period: "2015–2019", org: "Crossway CRO", role: "Data Coordinator", tenure: "4.0 yrs", scope: "Query mgmt", lang: "Reads RO-2, scope RO-2", signal: "Positive" },
      { type: "role", period: "2019–now", org: "Atlas Trials", role: "Clinical Data Manager", tenure: "6.0 yrs", scope: "Standard eCRF + query mgmt, mid-size studies", lang: "Reads RO-4, scope RO-3 — slightly inflated", signal: "Inflated" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I am a seasoned clinical data manager looking for my next opportunity to make an impact.", comment: 'Generic opener — "seasoned", "make an impact". Competent but says nothing specific about RDI.', kind: "thin" },
      ],
    },
    answers: [
      { q: "Q2 — Hardest lock?", a: "I have managed many locks across mid-size studies and pride myself on clean delivery.", comment: 'No specifics — "many locks", "pride myself". Reads as competent-generic; nothing differentiating to test.', kind: "thin" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Sherman Oaks, CA",
      distance: "~6 mi / 15 min",
      likelihood: "High",
      read: "Local to the Valley — short Van Nuys commute. Logistics are clean; the hold is about relevance, not feasibility.",
      signals: [{ mark: "+", t: "Sherman Oaks address — minutes from the lab." }],
    },
    redFlags: [],
  },

  // =================== PRIYA — hold / mismatch ===================
  {
    id: "priya",
    rank: 15,
    name: "Priya N.",
    role: "Senior Data Coordinator",
    company: "Cobalt CRO",
    salary: "$115k",
    salaryNum: 115,
    decision: "hold",
    rev: "none",
    revNote: "No human review yet.",
    why: "Coordinator-level depth at a manager-level ask; capable but not yet a lock owner.",
    flag: "Title/scope below the role; would need backstopping on lock decisions.",
    next: "Hold",
    survivor: false,
    askTier: "high",
    askNote: "manager-level ask",
    roLevel: "RO-2",
    roVsPool: "Coordinator — below the role bar",
    mismatch: true,
    mismatchRead:
      "Top-tier ask, relatively low RO level. Coordinator scope priced like a manager — the clearest ask/level mismatch in the pool.",
    timeline: [
      { type: "edu", period: "2013–2017", org: "UC Irvine", role: "BS, Biological Sciences", tenure: "4.0 yrs", scope: "Science degree — connects", lang: "—", signal: "Connected" },
      { type: "role", period: "2017–2021", org: "Cobalt CRO", role: "Data Coordinator", tenure: "4.0 yrs", scope: "Query handling, CRF tracking", lang: "Reads RO-2, scope RO-2", signal: "Positive" },
      { type: "role", period: "2021–now", org: "Cobalt CRO", role: "Senior Data Coordinator", tenure: "4.0 yrs", scope: "Coordinator scope, no independent lock ownership", lang: "Reads RO-4, scope RO-2 — inflated", signal: "Inflated" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I have owned the data coordination for some of Cobalt’s largest studies and am ready to step up.", comment: '"Owned coordination" of large studies — but the scope shown is coordinator, not manager. Language runs ahead of the role.', kind: "flag" },
      ],
    },
    answers: [
      { q: "Q2 — Describe a lock you owned.", a: "I coordinated the data flow and worked with the DM to get studies to lock on time.", comment: 'Tells on itself — "worked with the DM", i.e. did not own the lock. Confirms coordinator level despite the senior title.', kind: "flag" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Irvine, CA",
      distance: "~55 mi / 60–90 min",
      likelihood: "Low",
      read: "Orange County base — a brutal daily Van Nuys commute. Would likely need to relocate; no Valley ties on file.",
      signals: [{ mark: "–", t: "Irvine → Van Nuys is 60–90 min each way; 5-day on-site is a stretch." }],
    },
    redFlags: [],
  },

  // =================== GRACE — hold / Lara re-analysis ===================
  {
    id: "grace",
    rank: 16,
    name: "Grace O.",
    role: "Senior Clinical Data Manager",
    company: "Pinnacle Dx",
    salary: "$112k",
    salaryNum: 112,
    decision: "hold",
    rev: "laraConcern",
    revNote:
      "Rude / dismissive in Lara’s interview; management-burden risk if reporting to Lara. Was Interview first on materials alone.",
    why: "Strong EDC-migration file, but moved Interview → Hold after a direct Lara interview signal.",
    flag: "Management-burden risk from Lara’s direct observation; would likely report to Lara.",
    next: "Hold / reroute",
    survivor: false,
    askTier: "mid",
    askNote: "in-range for the file",
    roLevel: "RO-4",
    roVsPool: "Senior IC — strong on materials",
    mismatch: false,
    mismatchRead:
      "Ask and RO level line up well. The block is not comp or level — it is the human signal from Lara’s interview.",
    reanalysis: {
      reviewer: "Lara interview note",
      before: "Interview first",
      after: "Hold",
      rec: "Do not advance for a Lara-managed role unless Conall believes the concern was situational and runs a focused follow-up on humility and response to feedback.",
    },
    timeline: [
      { type: "edu", period: "2009–2013", org: "NYU", role: "BS, Chemistry", tenure: "4.0 yrs", scope: "Science degree — connects", lang: "—", signal: "Connected" },
      { type: "role", period: "2014–2020", org: "Helix Therapeutics", role: "Clinical Data Manager", tenure: "6.0 yrs", scope: "Owns study DM", lang: "Reads RO-3, scope RO-3 — matched", signal: "Positive" },
      { type: "role", period: "2020–now", org: "Pinnacle Dx", role: "Senior Clinical Data Manager", tenure: "5.0 yrs", scope: "Led EDC migration across 12 active studies, zero data loss", lang: "Reads RO-4, scope RO-4 — matched", signal: "Positive" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "I led an EDC platform migration across twelve active studies with zero data loss, and I want that scale of ownership at RDI.", comment: "Genuinely strong claim — migration without loss is hard. The materials earned an interview.", kind: "good" },
      ],
    },
    answers: [
      { q: "Q2 — Hardest cross-team project.", a: "I drove the migration over objections from study teams who wanted to keep the old system.", comment: '"Over objections" — strong delivery, but worth probing how she handles disagreement. Lara’s interview later flagged exactly this.', kind: "ask" },
    ],
    logistics: {
      mode: "In office — Van Nuys, 5 days",
      location: "Burbank, CA",
      distance: "~7 mi / 15 min",
      likelihood: "High",
      read: "Local — short commute. Logistics are not the issue; the human-signal concern is.",
      signals: [{ mark: "+", t: "Burbank address — minutes from Van Nuys." }],
    },
    fireflies: [
      { title: "Interview — Grace O. / Lara", date: "Apr 2, 2026", dur: "41 min", transcript: "Lara: Walk me through the EDC migration and where it got hard.\nGrace: Twelve studies, zero data loss. The study teams pushed back constantly — I just drove it over their objections.\nLara: How did you handle the disagreement?\nGrace: They were wrong. I do not have time to relitigate every decision with people who cannot see the whole board.\nLara (note): Came across as dismissive — talked over me twice and bristled when I pushed. Strong delivery, but real management-burden risk if she reports to me." },
    ],
    redFlags: [],
  },

  // =================== TOMÁS — blocked ===================
  {
    id: "tomas",
    rank: 17,
    name: "Tomás R.",
    role: "Clinical Data Manager",
    company: "Helios Bio",
    salary: "$104k",
    salaryNum: 104,
    decision: "blocked",
    rev: "none",
    revNote: "AI review not complete — no recommendation allowed.",
    why: "Résumé failed to parse and application answers are missing; AI review is incomplete.",
    flag: "No recommendation allowed until required review completes.",
    next: "Re-sync",
    survivor: false,
    askTier: "mid",
    askNote: "within range",
    roLevel: "—",
    roVsPool: "Cannot place — materials incomplete",
    mismatch: true,
    mismatchLabel: "Review blocked",
    mismatchRead:
      "Résumé failed to parse from Workable and answers did not sync. Re-sync before placing — no read is possible yet.",
    timeline: [
      { type: "role", period: "—", org: "Helios Bio", role: "Clinical Data Manager", tenure: "—", scope: "Résumé failed to parse — timeline unavailable", lang: "—", signal: "Ask" },
    ],
    cover: { hasLetter: false, lines: [] },
    answers: [],
    logistics: {
      mode: "Unknown — not synced",
      location: "Not parsed",
      distance: "Unknown",
      likelihood: "Medium",
      read: "Logistics cannot be assessed until materials re-sync from Workable.",
      signals: [],
    },
    redFlags: [],
  },

  // =================== GREGORY — cut / application care ===================
  {
    id: "gregory",
    rank: 31,
    name: "Gregory V.",
    role: "Controller",
    company: "Hartwell Industries",
    salary: "$90k",
    salaryNum: 90,
    decision: "cut",
    rev: "none",
    revNote: "No human review needed — application-quality failure cuts before any human time.",
    why: "Wrong-company cover letter and a Controller background — no relevance to the CDM role.",
    flag: "Application-care failure; wrong role entirely.",
    next: "Reject",
    survivor: false,
    cutGroup: "care",
    cutReason: "Cover letter addresses a different company; applying as a Controller, not a data manager.",
    cite: "Cover ¶1",
    cutMatters: "For a role built on care and detail, a wrong-company letter is a direct application-quality failure.",
    askTier: "mid",
    askNote: "irrelevant — wrong role",
    roLevel: "RO-4",
    roVsPool: "Finance level — not comparable to CDM",
    mismatch: true,
    mismatchLabel: "Wrong role",
    mismatchRead:
      "A corporate Controller applying to a clinical data role. RO level is real but in the wrong discipline entirely.",
    timeline: [
      { type: "edu", period: "2004–2008", org: "Arizona State", role: "BS, Accounting", tenure: "4.0 yrs", scope: "Finance degree — no science, no clinical", lang: "—", signal: "Switched" },
      { type: "role", period: "2008–2016", org: "Multiple", role: "Staff → Senior Accountant", tenure: "8.0 yrs", scope: "GAAP close, audit support", lang: "Reads RO-3, scope RO-3", signal: "Positive" },
      { type: "role", period: "2016–now", org: "Hartwell Industries", role: "Controller", tenure: "9.0 yrs", scope: "Corporate accounting — no clinical, no data mgmt", lang: "Reads RO-4, wrong field", signal: "Switched" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "Dear Brightpath Logistics hiring team, I am excited to apply for your Controller opening.", comment: 'Wrong company AND wrong role — addresses "Brightpath Logistics" and applies as a Controller. He didn’t even change the template.', kind: "wrong" },
        { t: "I bring fifteen years of GAAP close and audit experience to your finance organization.", comment: "Confirms it: this is a finance cover letter pasted into a clinical data application. Zero relevance.", kind: "flag" },
      ],
    },
    answers: [
      { q: "Q1 — Why this role?", a: "I am seeking a senior finance leadership position where I can own the close process.", comment: "Answer is about a finance job. Nothing here engages with clinical data at all.", kind: "flag" },
    ],
    logistics: {
      mode: "Not assessed — cut on materials",
      location: "Phoenix, AZ",
      distance: "N/A",
      likelihood: "Low",
      read: "Not worth a logistics check — the application is for a different role at a different company.",
      signals: [],
    },
    redFlags: [
      { flag: "Wrong company", detail: 'Cover letter opens "Dear Brightpath Logistics hiring team" — a different company entirely.', source: "Cover ¶1" },
      { flag: "Wrong role", detail: "Applying as a Controller; résumé is corporate accounting with no clinical or data-management work.", source: "Résumé" },
      { flag: "No template care", detail: "Reused a finance cover letter without editing the company or role — a direct application-quality failure.", source: "Cover ¶1–2" },
    ],
  },

  // =================== BRAD — cut / application care ===================
  {
    id: "brad",
    rank: 32,
    name: "Brad M.",
    role: "Data Analyst",
    company: "Onyx Data",
    salary: "$98k",
    salaryNum: 98,
    decision: "cut",
    rev: "none",
    revNote: "No human review needed.",
    why: "Generic AI-looking answers with no concrete examples.",
    flag: "Low care; no specific evidence anywhere.",
    next: "Reject",
    survivor: false,
    cutGroup: "care",
    cutReason: "Every application answer is generic and templated; no concrete example in the whole file.",
    cite: "Q1–Q3",
    cutMatters: "No concrete evidence anywhere — nothing to interview against, and low care signals low care on the job.",
    askTier: "mid",
    askNote: "irrelevant — no evidence",
    roLevel: "RO-2",
    roVsPool: "Junior — and unverifiable",
    mismatch: true,
    mismatchLabel: "No evidence",
    mismatchRead:
      "Answers read as AI-generated boilerplate — nothing concrete to verify a level against.",
    timeline: [
      { type: "edu", period: "2015–2019", org: "Generic State U", role: "BS, Business Analytics", tenure: "4.0 yrs", scope: "Adjacent degree — no clinical", lang: "—", signal: "Switched" },
      { type: "role", period: "2019–now", org: "Onyx Data", role: "Data Analyst", tenure: "6.0 yrs", scope: "Dashboards and reporting — no clinical, no EDC", lang: "Reads RO-2, scope RO-2", signal: "Positive" },
    ],
    cover: { hasLetter: false, lines: [] },
    answers: [
      { q: "Q1 — Why this role?", a: "I am a detail-oriented team player passionate about data quality and driving impact in a fast-paced environment.", comment: 'Textbook AI / template language — "detail-oriented team player", "driving impact", "fast-paced". No specific example anywhere.', kind: "ai" },
      { q: "Q2 — Biggest win?", a: "I leveraged data to deliver actionable insights that moved the needle for stakeholders.", comment: 'Pure buzzword filler — "leveraged", "actionable insights", "moved the needle". Nothing real to test.', kind: "ai" },
    ],
    logistics: {
      mode: "Not assessed — cut on materials",
      location: "Austin, TX",
      distance: "N/A",
      likelihood: "Low",
      read: "Not worth a logistics check — no concrete evidence to interview against.",
      signals: [],
    },
    redFlags: [
      { flag: "AI-written answers", detail: "All three answers are generic, buzzword-dense, and example-free — reads as AI-generated boilerplate.", source: "Q1–Q3" },
      { flag: "No concrete evidence", detail: "Not one specific project, metric, or mechanic in the entire application.", source: "Application" },
      { flag: "No cover letter", detail: "No letter submitted to offset the thin answers.", source: "Cover" },
    ],
  },

  // =================== LINDSAY — cut / evidence ===================
  {
    id: "lindsay",
    rank: 33,
    name: "Lindsay C.",
    role: "Clinical Data Manager",
    company: "Vantage CRO",
    salary: "$110k",
    salaryNum: 110,
    decision: "cut",
    rev: "none",
    revNote: "No human review needed.",
    why: "Résumé and application contradict each other on dates and scope.",
    flag: "Resume/application contradiction undermines trust.",
    next: "Reject",
    survivor: false,
    cutGroup: "evidence",
    cutReason: "Résumé shows 2021–2023 at Vantage; application says 2019–2024 with a different title.",
    cite: "Résumé vs Q1",
    cutMatters: "For a data-integrity role, an unexplained factual contradiction is disqualifying.",
    askTier: "mid",
    askNote: "irrelevant — contradicted file",
    roLevel: "RO-3?",
    roVsPool: "Unclear — the file contradicts itself",
    mismatch: true,
    mismatchLabel: "Contradiction",
    mismatchRead:
      "Résumé and application disagree on dates and title at the same company. For a data-integrity role, an unexplained factual contradiction is disqualifying.",
    timeline: [
      { type: "edu", period: "2013–2017", org: "Penn State", role: "BS, Biology", tenure: "4.0 yrs", scope: "Science degree — connects", lang: "—", signal: "Connected" },
      { type: "role", period: "2021–2023", org: "Vantage CRO", role: "CDM (per résumé)", tenure: "2.0 yrs", scope: "Résumé dates", lang: "Reads RO-3", signal: "Positive" },
      { type: "gap", period: "2019–2024?", org: "Vantage CRO", role: "Senior CDM (per application)", tenure: "conflict", scope: "Application claims different dates and a higher title — unexplained conflict", lang: "—", signal: "Gap" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "In my five years as Senior Clinical Data Manager at Vantage, I built the data function from the ground up.", comment: "Letter says five years as Senior CDM; the résumé says two years as CDM. The story doesn’t reconcile.", kind: "flag" },
      ],
    },
    answers: [
      { q: "Q1 — Current role and tenure?", a: "Senior Clinical Data Manager at Vantage CRO, 2019–2024.", comment: "Directly contradicts the résumé (CDM, 2021–2023). Different dates, different title, same employer — unexplained.", kind: "flag" },
    ],
    logistics: {
      mode: "Not assessed — cut on materials",
      location: "Philadelphia, PA",
      distance: "N/A",
      likelihood: "Low",
      read: "Not worth a logistics check — the contradiction is disqualifying first.",
      signals: [],
    },
    redFlags: [
      { flag: "Résumé / app contradiction", detail: "Résumé: CDM 2021–2023. Application: Senior CDM 2019–2024. Same company, conflicting dates and title.", source: "Résumé vs Q1" },
      { flag: "Inflated title in letter", detail: "Cover letter claims five years as Senior CDM — unsupported by the résumé.", source: "Cover ¶1" },
    ],
  },

  // =================== NADIA — cut / career pattern ===================
  {
    id: "nadia",
    rank: 34,
    name: "Nadia P.",
    role: "Data Manager",
    company: "(various)",
    salary: "$102k",
    salaryNum: 102,
    decision: "cut",
    rev: "none",
    revNote: "No human review needed.",
    why: "Five roles in four years, none over 11 months, no explanation.",
    flag: "Repeated short tenures with no narrative.",
    next: "Reject",
    survivor: false,
    cutGroup: "pattern",
    cutReason: "Five positions in four years, longest 11 months, no explanation in cover or answers.",
    cite: "Timeline",
    cutMatters: "CDM continuity through a lock cycle is the job; unexplained churn is the core risk.",
    askTier: "mid",
    askNote: "irrelevant — pattern risk",
    roLevel: "RO-3",
    roVsPool: "Mid — but no continuity through a lock",
    mismatch: true,
    mismatchLabel: "Pattern risk",
    mismatchRead:
      "Five roles in four years, longest 11 months, none explained. CDM continuity through lock is the job — the pattern is the disqualifier.",
    timeline: [
      { type: "edu", period: "2011–2015", org: "Michigan State", role: "BS, Biology", tenure: "4.0 yrs", scope: "Science degree — connects", lang: "—", signal: "Connected" },
      { type: "role", period: "2021", org: "Firm A", role: "Data Manager", tenure: "0.8 yr", scope: "Left before a full lock cycle", lang: "—", signal: "Gap" },
      { type: "gap", period: "2021–2022", org: "—", role: "Gap", tenure: "4 mos", scope: "Unexplained break between roles", lang: "—", signal: "Gap" },
      { type: "role", period: "2022", org: "Firm B", role: "Data Manager", tenure: "0.9 yr", scope: "Short tenure, no narrative", lang: "—", signal: "Gap" },
      { type: "role", period: "2023–now", org: "Firms C–E", role: "Data Manager (×3)", tenure: "<1 yr each", scope: "Three more sub-year stints, no explanation offered", lang: "—", signal: "Gap" },
    ],
    cover: { hasLetter: false, lines: [] },
    answers: [
      { q: "Q1 — Walk us through your recent moves.", a: "I have worked across several organizations to broaden my experience.", comment: '"Broaden my experience" does not explain five sub-year roles and a gap. The pattern is unaddressed.', kind: "flag" },
    ],
    logistics: {
      mode: "Not assessed — cut on materials",
      location: "Chicago, IL",
      distance: "N/A",
      likelihood: "Low",
      read: "Not worth a logistics check — the tenure pattern is the disqualifier.",
      signals: [],
    },
    redFlags: [
      { flag: "Repeated short tenures", detail: "Five roles in four years, longest 11 months — no continuity through a lock cycle.", source: "Timeline" },
      { flag: "Unexplained gap", detail: "A 4-month break between roles with no narrative in the application.", source: "Timeline" },
      { flag: "No explanation offered", detail: "Cover letter absent; the one answer that touches it is a non-answer.", source: "Q1" },
    ],
  },

  // =================== OWEN — cut / role mismatch ===================
  {
    id: "owen",
    rank: 35,
    name: "Owen P.",
    role: "Business Analyst",
    company: "Delta Systems",
    salary: "$95k",
    salaryNum: 95,
    decision: "cut",
    rev: "none",
    revNote: "No human review needed.",
    why: "General BA background; does not remove the role’s core data-integrity burden.",
    flag: "Would need too much backstopping to be useful.",
    next: "Reject",
    survivor: false,
    cutGroup: "mismatch",
    cutReason: "General business-analyst path; no EDC, no clinical, no lock experience.",
    cite: "Résumé",
    cutMatters: "Would need backstopping in exactly the area the role exists to cover.",
    askTier: "mid",
    askNote: "irrelevant — wrong burden",
    roLevel: "RO-3",
    roVsPool: "Mid — but not in clinical data",
    mismatch: true,
    mismatchLabel: "Role mismatch",
    mismatchRead:
      "A general business analyst with no EDC, clinical, or lock experience. Would need to be built from zero in the one area the role is about.",
    timeline: [
      { type: "edu", period: "2012–2016", org: "University of Texas", role: "BS, Information Systems", tenure: "4.0 yrs", scope: "IT degree — no science, no clinical", lang: "—", signal: "Switched" },
      { type: "role", period: "2016–now", org: "Delta Systems", role: "Business Analyst", tenure: "9.0 yrs", scope: "Dashboards, requirements gathering — no clinical data", lang: "Reads RO-3, wrong field", signal: "Switched" },
    ],
    cover: {
      hasLetter: true,
      lines: [
        { t: "My analytical background makes me a strong fit for any data-focused role.", comment: '"Any data-focused role" — generic and tells on itself. No EDC, no clinical, no lock; this is not that kind of data role.', kind: "thin" },
      ],
    },
    answers: [
      { q: "Q2 — Clinical data / EDC experience?", a: "While I have not worked in clinical trials directly, my analytics skills transfer.", comment: "Concedes no clinical or EDC experience. The transfer claim is thin — RDI would backstop the entire core of the role.", kind: "flag" },
    ],
    logistics: {
      mode: "Not assessed — cut on materials",
      location: "Dallas, TX",
      distance: "N/A",
      likelihood: "Low",
      read: "Not worth a logistics check — does not remove the role’s core burden.",
      signals: [],
    },
    redFlags: [
      { flag: "Does not remove core burden", detail: "General BA work; no EDC, clinical, or lock experience — backstopping required in exactly the area the role exists for.", source: "Résumé" },
      { flag: "Generic fit claim", detail: '"Strong fit for any data-focused role" — no engagement with what clinical data management actually is.', source: "Cover ¶1" },
    ],
  },
];

export const POOL_TITLE = "CDM pool";
export const JOB_CODE = "RDI-CDM-021";
export const HEALTH_STATE = "Usable, not strong";
export const HEALTH_READ =
  "Usable but not strong. One standout data file, one strong hybrid, no perfect IVD fit — clear the cut list first, then screen the top group and keep recruiting.";

export function findCandidate(id: string): Candidate {
  return CANDIDATES.find((c) => c.id === id) || CANDIDATES[0];
}
